---
- name: Agregar usuario Prometheus.
  user:
    name: prometheus
    shell: /bin/false
    system: true
    create_home: no

- name: Crear carpeta Prometheus	
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Crear carpeta BD Prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Descargar y extraer.
  unarchive:
    src: '{{ prometheus }}'
    dest: /tmp
    remote_src: yes

- name: Copiar binarios promtool al /usr/local/bin
  copy:
    src: '/tmp/{{ prometheus_version }}/promtool'
    dest: /usr/local/bin/
    remote_src: yes
    mode: u+x,g+x,o+x

- name: Copiar binarios prometheus al /usr/local/bin
  copy:
    src: '/tmp/{{ prometheus_version }}/prometheus'
    dest: /usr/local/bin/
    remote_src: yes
    mode: u+x,g+x,o+x

- name: Crear archivo de conf Prometheus.yml
  file:
    path: /etc/prometheus/prometheus.yml
    state: touch
    owner: prometheus
    group: prometheus
    mode: u=rw,g=rw,o=r

- name: Crear archivo de conf de servicio Prometheus
  file:
    path: /etc/systemd/system/prometheus.service
    state: touch
    mode: u=rw,g=rw,o=r

- name: Cargar conf prometheus.yml 
  template:
    src: produccion/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml 
    owner: prometheus
    group: prometheus
    mode: u+x,g+x,o+x

- name: Cargar conf de servicio Prometheus.
  template:
    src: produccion/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Systemctl reload
  systemd: 
    daemon_reload: yes

- name: Iniciar servicios Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Agregar permisos al puerto en el firewall.
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled

- name: Forzar cambios en el firewall.
  systemd:
    name: firewalld
    state: reloaded
  
- name: Chequear que el puerto 9090 este disponible.
  wait_for:
    port: 9090
    state: started
    timeout: 10